///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PokemonDetailModelTypesType {
/*
{
  "name": "normal",
  "url": "https://pokeapi.co/api/v2/type/1/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelTypesType({
    this.name,
    this.url,
  });
  PokemonDetailModelTypesType.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelTypes {
/*
{
  "slot": 1,
  "type": {
    "name": "normal",
    "url": "https://pokeapi.co/api/v2/type/1/"
  }
} 
*/

  int? slot;
  PokemonDetailModelTypesType? type;

  PokemonDetailModelTypes({
    this.slot,
    this.type,
  });
  PokemonDetailModelTypes.fromJson(Map<String, dynamic> json) {
    slot = json['slot']?.toInt();
    type = (json['type'] != null) ? PokemonDetailModelTypesType.fromJson(json['type']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['slot'] = slot;
    if (type != null) {
      data['type'] = type!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelStatsStat {
/*
{
  "name": "hp",
  "url": "https://pokeapi.co/api/v2/stat/1/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelStatsStat({
    this.name,
    this.url,
  });
  PokemonDetailModelStatsStat.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelStats {
/*
{
  "base_stat": 40,
  "effort": 0,
  "stat": {
    "name": "hp",
    "url": "https://pokeapi.co/api/v2/stat/1/"
  }
} 
*/

  int? baseStat;
  int? effort;
  PokemonDetailModelStatsStat? stat;

  PokemonDetailModelStats({
    this.baseStat,
    this.effort,
    this.stat,
  });
  PokemonDetailModelStats.fromJson(Map<String, dynamic> json) {
    baseStat = json['base_stat']?.toInt();
    effort = json['effort']?.toInt();
    stat = (json['stat'] != null) ? PokemonDetailModelStatsStat.fromJson(json['stat']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['base_stat'] = baseStat;
    data['effort'] = effort;
    if (stat != null) {
      data['stat'] = stat!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationViiiIcons {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/21.png",
  "front_female": null
} 
*/

  String? frontDefault;
  String? frontFemale;

  PokemonDetailModelSpritesVersionsGenerationViiiIcons({
    this.frontDefault,
    this.frontFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationViiiIcons.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationViii {
/*
{
  "icons": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-viii/icons/21.png",
    "front_female": null
  }
} 
*/

  PokemonDetailModelSpritesVersionsGenerationViiiIcons? icons;

  PokemonDetailModelSpritesVersionsGenerationViii({
    this.icons,
  });
  PokemonDetailModelSpritesVersionsGenerationViii.fromJson(Map<String, dynamic> json) {
    icons = (json['icons'] != null) ? PokemonDetailModelSpritesVersionsGenerationViiiIcons.fromJson(json['icons']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (icons != null) {
      data['icons'] = icons!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationViiUltraSunUltraMoon {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/shiny/21.png",
  "front_shiny_female": null
} 
*/

  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationViiUltraSunUltraMoon({
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationViiUltraSunUltraMoon.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationViiIcons {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/icons/21.png",
  "front_female": null
} 
*/

  String? frontDefault;
  String? frontFemale;

  PokemonDetailModelSpritesVersionsGenerationViiIcons({
    this.frontDefault,
    this.frontFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationViiIcons.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationVii {
/*
{
  "icons": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/icons/21.png",
    "front_female": null
  },
  "ultra-sun-ultra-moon": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vii/ultra-sun-ultra-moon/shiny/21.png",
    "front_shiny_female": null
  }
} 
*/

  PokemonDetailModelSpritesVersionsGenerationViiIcons? icons;
  PokemonDetailModelSpritesVersionsGenerationViiUltraSunUltraMoon? ultraSunUltraMoon;

  PokemonDetailModelSpritesVersionsGenerationVii({
    this.icons,
    this.ultraSunUltraMoon,
  });
  PokemonDetailModelSpritesVersionsGenerationVii.fromJson(Map<String, dynamic> json) {
    icons = (json['icons'] != null) ? PokemonDetailModelSpritesVersionsGenerationViiIcons.fromJson(json['icons']) : null;
    ultraSunUltraMoon = (json['ultra-sun-ultra-moon'] != null) ? PokemonDetailModelSpritesVersionsGenerationViiUltraSunUltraMoon.fromJson(json['ultra-sun-ultra-moon']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (icons != null) {
      data['icons'] = icons!.toJson();
    }
    if (ultraSunUltraMoon != null) {
      data['ultra-sun-ultra-moon'] = ultraSunUltraMoon!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationViXY {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/shiny/21.png",
  "front_shiny_female": null
} 
*/

  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationViXY({
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationViXY.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationViOmegarubyAlphasapphire {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/shiny/21.png",
  "front_shiny_female": null
} 
*/

  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationViOmegarubyAlphasapphire({
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationViOmegarubyAlphasapphire.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationVi {
/*
{
  "omegaruby-alphasapphire": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/omegaruby-alphasapphire/shiny/21.png",
    "front_shiny_female": null
  },
  "x-y": {
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-vi/x-y/shiny/21.png",
    "front_shiny_female": null
  }
} 
*/

  PokemonDetailModelSpritesVersionsGenerationViOmegarubyAlphasapphire? omegarubyAlphasapphire;
  PokemonDetailModelSpritesVersionsGenerationViXY? xY;

  PokemonDetailModelSpritesVersionsGenerationVi({
    this.omegarubyAlphasapphire,
    this.xY,
  });
  PokemonDetailModelSpritesVersionsGenerationVi.fromJson(Map<String, dynamic> json) {
    omegarubyAlphasapphire = (json['omegaruby-alphasapphire'] != null) ? PokemonDetailModelSpritesVersionsGenerationViOmegarubyAlphasapphire.fromJson(json['omegaruby-alphasapphire']) : null;
    xY = (json['x-y'] != null) ? PokemonDetailModelSpritesVersionsGenerationViXY.fromJson(json['x-y']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (omegarubyAlphasapphire != null) {
      data['omegaruby-alphasapphire'] = omegarubyAlphasapphire!.toJson();
    }
    if (xY != null) {
      data['x-y'] = xY!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationVBlackWhiteAnimated {
/*
{
  "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/21.gif",
  "back_female": null,
  "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/21.gif",
  "back_shiny_female": null,
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/21.gif",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/21.gif",
  "front_shiny_female": null
} 
*/

  String? backDefault;
  String? backFemale;
  String? backShiny;
  String? backShinyFemale;
  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationVBlackWhiteAnimated({
    this.backDefault,
    this.backFemale,
    this.backShiny,
    this.backShinyFemale,
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationVBlackWhiteAnimated.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backFemale = json['back_female']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyFemale = json['back_shiny_female']?.toString();
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_female'] = backFemale;
    data['back_shiny'] = backShiny;
    data['back_shiny_female'] = backShinyFemale;
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationVBlackWhite {
/*
{
  "animated": {
    "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/21.gif",
    "back_female": null,
    "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/21.gif",
    "back_shiny_female": null,
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/21.gif",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/21.gif",
    "front_shiny_female": null
  },
  "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/21.png",
  "back_female": null,
  "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/shiny/21.png",
  "back_shiny_female": null,
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/shiny/21.png",
  "front_shiny_female": null
} 
*/

  PokemonDetailModelSpritesVersionsGenerationVBlackWhiteAnimated? animated;
  String? backDefault;
  String? backFemale;
  String? backShiny;
  String? backShinyFemale;
  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationVBlackWhite({
    this.animated,
    this.backDefault,
    this.backFemale,
    this.backShiny,
    this.backShinyFemale,
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationVBlackWhite.fromJson(Map<String, dynamic> json) {
    animated = (json['animated'] != null) ? PokemonDetailModelSpritesVersionsGenerationVBlackWhiteAnimated.fromJson(json['animated']) : null;
    backDefault = json['back_default']?.toString();
    backFemale = json['back_female']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyFemale = json['back_shiny_female']?.toString();
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (animated != null) {
      data['animated'] = animated!.toJson();
    }
    data['back_default'] = backDefault;
    data['back_female'] = backFemale;
    data['back_shiny'] = backShiny;
    data['back_shiny_female'] = backShinyFemale;
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationV {
/*
{
  "black-white": {
    "animated": {
      "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/21.gif",
      "back_female": null,
      "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/back/shiny/21.gif",
      "back_shiny_female": null,
      "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/21.gif",
      "front_female": null,
      "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/animated/shiny/21.gif",
      "front_shiny_female": null
    },
    "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/21.png",
    "back_female": null,
    "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/back/shiny/21.png",
    "back_shiny_female": null,
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-v/black-white/shiny/21.png",
    "front_shiny_female": null
  }
} 
*/

  PokemonDetailModelSpritesVersionsGenerationVBlackWhite? blackWhite;

  PokemonDetailModelSpritesVersionsGenerationV({
    this.blackWhite,
  });
  PokemonDetailModelSpritesVersionsGenerationV.fromJson(Map<String, dynamic> json) {
    blackWhite = (json['black-white'] != null) ? PokemonDetailModelSpritesVersionsGenerationVBlackWhite.fromJson(json['black-white']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (blackWhite != null) {
      data['black-white'] = blackWhite!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIvPlatinum {
/*
{
  "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/21.png",
  "back_female": null,
  "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/shiny/21.png",
  "back_shiny_female": null,
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/shiny/21.png",
  "front_shiny_female": null
} 
*/

  String? backDefault;
  String? backFemale;
  String? backShiny;
  String? backShinyFemale;
  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationIvPlatinum({
    this.backDefault,
    this.backFemale,
    this.backShiny,
    this.backShinyFemale,
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationIvPlatinum.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backFemale = json['back_female']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyFemale = json['back_shiny_female']?.toString();
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_female'] = backFemale;
    data['back_shiny'] = backShiny;
    data['back_shiny_female'] = backShinyFemale;
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIvHeartgoldSoulsilver {
/*
{
  "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/21.png",
  "back_female": null,
  "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/shiny/21.png",
  "back_shiny_female": null,
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/shiny/21.png",
  "front_shiny_female": null
} 
*/

  String? backDefault;
  String? backFemale;
  String? backShiny;
  String? backShinyFemale;
  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationIvHeartgoldSoulsilver({
    this.backDefault,
    this.backFemale,
    this.backShiny,
    this.backShinyFemale,
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationIvHeartgoldSoulsilver.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backFemale = json['back_female']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyFemale = json['back_shiny_female']?.toString();
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_female'] = backFemale;
    data['back_shiny'] = backShiny;
    data['back_shiny_female'] = backShinyFemale;
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIvDiamondPearl {
/*
{
  "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/21.png",
  "back_female": null,
  "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/shiny/21.png",
  "back_shiny_female": null,
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/21.png",
  "front_female": null,
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/shiny/21.png",
  "front_shiny_female": null
} 
*/

  String? backDefault;
  String? backFemale;
  String? backShiny;
  String? backShinyFemale;
  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesVersionsGenerationIvDiamondPearl({
    this.backDefault,
    this.backFemale,
    this.backShiny,
    this.backShinyFemale,
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesVersionsGenerationIvDiamondPearl.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backFemale = json['back_female']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyFemale = json['back_shiny_female']?.toString();
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_female'] = backFemale;
    data['back_shiny'] = backShiny;
    data['back_shiny_female'] = backShinyFemale;
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIv {
/*
{
  "diamond-pearl": {
    "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/21.png",
    "back_female": null,
    "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/back/shiny/21.png",
    "back_shiny_female": null,
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/diamond-pearl/shiny/21.png",
    "front_shiny_female": null
  },
  "heartgold-soulsilver": {
    "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/21.png",
    "back_female": null,
    "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/back/shiny/21.png",
    "back_shiny_female": null,
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/heartgold-soulsilver/shiny/21.png",
    "front_shiny_female": null
  },
  "platinum": {
    "back_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/21.png",
    "back_female": null,
    "back_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/back/shiny/21.png",
    "back_shiny_female": null,
    "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/21.png",
    "front_female": null,
    "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iv/platinum/shiny/21.png",
    "front_shiny_female": null
  }
} 
*/

  PokemonDetailModelSpritesVersionsGenerationIvDiamondPearl? diamondPearl;
  PokemonDetailModelSpritesVersionsGenerationIvHeartgoldSoulsilver? heartgoldSoulsilver;
  PokemonDetailModelSpritesVersionsGenerationIvPlatinum? platinum;

  PokemonDetailModelSpritesVersionsGenerationIv({
    this.diamondPearl,
    this.heartgoldSoulsilver,
    this.platinum,
  });
  PokemonDetailModelSpritesVersionsGenerationIv.fromJson(Map<String, dynamic> json) {
    diamondPearl = (json['diamond-pearl'] != null) ? PokemonDetailModelSpritesVersionsGenerationIvDiamondPearl.fromJson(json['diamond-pearl']) : null;
    heartgoldSoulsilver = (json['heartgold-soulsilver'] != null) ? PokemonDetailModelSpritesVersionsGenerationIvHeartgoldSoulsilver.fromJson(json['heartgold-soulsilver']) : null;
    platinum = (json['platinum'] != null) ? PokemonDetailModelSpritesVersionsGenerationIvPlatinum.fromJson(json['platinum']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (diamondPearl != null) {
      data['diamond-pearl'] = diamondPearl!.toJson();
    }
    if (heartgoldSoulsilver != null) {
      data['heartgold-soulsilver'] = heartgoldSoulsilver!.toJson();
    }
    if (platinum != null) {
      data['platinum'] = platinum!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIiiRubySapphire {

  String? backDefault;
  String? backShiny;
  String? frontDefault;
  String? frontShiny;

  PokemonDetailModelSpritesVersionsGenerationIiiRubySapphire({
    this.backDefault,
    this.backShiny,
    this.frontDefault,
    this.frontShiny,
  });
  PokemonDetailModelSpritesVersionsGenerationIiiRubySapphire.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backShiny = json['back_shiny']?.toString();
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_shiny'] = backShiny;
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIiiFireredLeafgreen {

  String? backDefault;
  String? backShiny;
  String? frontDefault;
  String? frontShiny;

  PokemonDetailModelSpritesVersionsGenerationIiiFireredLeafgreen({
    this.backDefault,
    this.backShiny,
    this.frontDefault,
    this.frontShiny,
  });
  PokemonDetailModelSpritesVersionsGenerationIiiFireredLeafgreen.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backShiny = json['back_shiny']?.toString();
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_shiny'] = backShiny;
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIiiEmerald {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/21.png",
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/versions/generation-iii/emerald/shiny/21.png"
} 
*/

  String? frontDefault;
  String? frontShiny;

  PokemonDetailModelSpritesVersionsGenerationIiiEmerald({
    this.frontDefault,
    this.frontShiny,
  });
  PokemonDetailModelSpritesVersionsGenerationIiiEmerald.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIii {

  PokemonDetailModelSpritesVersionsGenerationIiiEmerald? emerald;
  PokemonDetailModelSpritesVersionsGenerationIiiFireredLeafgreen? fireredLeafgreen;
  PokemonDetailModelSpritesVersionsGenerationIiiRubySapphire? rubySapphire;

  PokemonDetailModelSpritesVersionsGenerationIii({
    this.emerald,
    this.fireredLeafgreen,
    this.rubySapphire,
  });
  PokemonDetailModelSpritesVersionsGenerationIii.fromJson(Map<String, dynamic> json) {
    emerald = (json['emerald'] != null) ? PokemonDetailModelSpritesVersionsGenerationIiiEmerald.fromJson(json['emerald']) : null;
    fireredLeafgreen = (json['firered-leafgreen'] != null) ? PokemonDetailModelSpritesVersionsGenerationIiiFireredLeafgreen.fromJson(json['firered-leafgreen']) : null;
    rubySapphire = (json['ruby-sapphire'] != null) ? PokemonDetailModelSpritesVersionsGenerationIiiRubySapphire.fromJson(json['ruby-sapphire']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (emerald != null) {
      data['emerald'] = emerald!.toJson();
    }
    if (fireredLeafgreen != null) {
      data['firered-leafgreen'] = fireredLeafgreen!.toJson();
    }
    if (rubySapphire != null) {
      data['ruby-sapphire'] = rubySapphire!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIiSilver {

  String? backDefault;
  String? backShiny;
  String? frontDefault;
  String? frontShiny;
  String? frontTransparent;

  PokemonDetailModelSpritesVersionsGenerationIiSilver({
    this.backDefault,
    this.backShiny,
    this.frontDefault,
    this.frontShiny,
    this.frontTransparent,
  });
  PokemonDetailModelSpritesVersionsGenerationIiSilver.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backShiny = json['back_shiny']?.toString();
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontTransparent = json['front_transparent']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_shiny'] = backShiny;
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    data['front_transparent'] = frontTransparent;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIiGold {

  String? backDefault;
  String? backShiny;
  String? frontDefault;
  String? frontShiny;
  String? frontTransparent;

  PokemonDetailModelSpritesVersionsGenerationIiGold({
    this.backDefault,
    this.backShiny,
    this.frontDefault,
    this.frontShiny,
    this.frontTransparent,
  });
  PokemonDetailModelSpritesVersionsGenerationIiGold.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backShiny = json['back_shiny']?.toString();
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontTransparent = json['front_transparent']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_shiny'] = backShiny;
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    data['front_transparent'] = frontTransparent;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIiCrystal {

  String? backDefault;
  String? backShiny;
  String? backShinyTransparent;
  String? backTransparent;
  String? frontDefault;
  String? frontShiny;
  String? frontShinyTransparent;
  String? frontTransparent;

  PokemonDetailModelSpritesVersionsGenerationIiCrystal({
    this.backDefault,
    this.backShiny,
    this.backShinyTransparent,
    this.backTransparent,
    this.frontDefault,
    this.frontShiny,
    this.frontShinyTransparent,
    this.frontTransparent,
  });
  PokemonDetailModelSpritesVersionsGenerationIiCrystal.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyTransparent = json['back_shiny_transparent']?.toString();
    backTransparent = json['back_transparent']?.toString();
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyTransparent = json['front_shiny_transparent']?.toString();
    frontTransparent = json['front_transparent']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_shiny'] = backShiny;
    data['back_shiny_transparent'] = backShinyTransparent;
    data['back_transparent'] = backTransparent;
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    data['front_shiny_transparent'] = frontShinyTransparent;
    data['front_transparent'] = frontTransparent;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIi {

  PokemonDetailModelSpritesVersionsGenerationIiCrystal? crystal;
  PokemonDetailModelSpritesVersionsGenerationIiGold? gold;
  PokemonDetailModelSpritesVersionsGenerationIiSilver? silver;

  PokemonDetailModelSpritesVersionsGenerationIi({
    this.crystal,
    this.gold,
    this.silver,
  });
  PokemonDetailModelSpritesVersionsGenerationIi.fromJson(Map<String, dynamic> json) {
    crystal = (json['crystal'] != null) ? PokemonDetailModelSpritesVersionsGenerationIiCrystal.fromJson(json['crystal']) : null;
    gold = (json['gold'] != null) ? PokemonDetailModelSpritesVersionsGenerationIiGold.fromJson(json['gold']) : null;
    silver = (json['silver'] != null) ? PokemonDetailModelSpritesVersionsGenerationIiSilver.fromJson(json['silver']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (crystal != null) {
      data['crystal'] = crystal!.toJson();
    }
    if (gold != null) {
      data['gold'] = gold!.toJson();
    }
    if (silver != null) {
      data['silver'] = silver!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIYellow {

  String? backDefault;
  String? backGray;
  String? backTransparent;
  String? frontDefault;
  String? frontGray;
  String? frontTransparent;

  PokemonDetailModelSpritesVersionsGenerationIYellow({
    this.backDefault,
    this.backGray,
    this.backTransparent,
    this.frontDefault,
    this.frontGray,
    this.frontTransparent,
  });
  PokemonDetailModelSpritesVersionsGenerationIYellow.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backGray = json['back_gray']?.toString();
    backTransparent = json['back_transparent']?.toString();
    frontDefault = json['front_default']?.toString();
    frontGray = json['front_gray']?.toString();
    frontTransparent = json['front_transparent']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_gray'] = backGray;
    data['back_transparent'] = backTransparent;
    data['front_default'] = frontDefault;
    data['front_gray'] = frontGray;
    data['front_transparent'] = frontTransparent;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationIRedBlue {

  String? backDefault;
  String? backGray;
  String? backTransparent;
  String? frontDefault;
  String? frontGray;
  String? frontTransparent;

  PokemonDetailModelSpritesVersionsGenerationIRedBlue({
    this.backDefault,
    this.backGray,
    this.backTransparent,
    this.frontDefault,
    this.frontGray,
    this.frontTransparent,
  });
  PokemonDetailModelSpritesVersionsGenerationIRedBlue.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backGray = json['back_gray']?.toString();
    backTransparent = json['back_transparent']?.toString();
    frontDefault = json['front_default']?.toString();
    frontGray = json['front_gray']?.toString();
    frontTransparent = json['front_transparent']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_gray'] = backGray;
    data['back_transparent'] = backTransparent;
    data['front_default'] = frontDefault;
    data['front_gray'] = frontGray;
    data['front_transparent'] = frontTransparent;
    return data;
  }
}

class PokemonDetailModelSpritesVersionsGenerationI {

  PokemonDetailModelSpritesVersionsGenerationIRedBlue? redBlue;
  PokemonDetailModelSpritesVersionsGenerationIYellow? yellow;

  PokemonDetailModelSpritesVersionsGenerationI({
    this.redBlue,
    this.yellow,
  });
  PokemonDetailModelSpritesVersionsGenerationI.fromJson(Map<String, dynamic> json) {
    redBlue = (json['red-blue'] != null) ? PokemonDetailModelSpritesVersionsGenerationIRedBlue.fromJson(json['red-blue']) : null;
    yellow = (json['yellow'] != null) ? PokemonDetailModelSpritesVersionsGenerationIYellow.fromJson(json['yellow']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (redBlue != null) {
      data['red-blue'] = redBlue!.toJson();
    }
    if (yellow != null) {
      data['yellow'] = yellow!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesVersions {

  PokemonDetailModelSpritesVersionsGenerationI? generationI;
  PokemonDetailModelSpritesVersionsGenerationIi? generationIi;
  PokemonDetailModelSpritesVersionsGenerationIii? generationIii;
  PokemonDetailModelSpritesVersionsGenerationIv? generationIv;
  PokemonDetailModelSpritesVersionsGenerationV? generationV;
  PokemonDetailModelSpritesVersionsGenerationVi? generationVi;
  PokemonDetailModelSpritesVersionsGenerationVii? generationVii;
  PokemonDetailModelSpritesVersionsGenerationViii? generationViii;

  PokemonDetailModelSpritesVersions({
    this.generationI,
    this.generationIi,
    this.generationIii,
    this.generationIv,
    this.generationV,
    this.generationVi,
    this.generationVii,
    this.generationViii,
  });
  PokemonDetailModelSpritesVersions.fromJson(Map<String, dynamic> json) {
    generationI = (json['generation-i'] != null) ? PokemonDetailModelSpritesVersionsGenerationI.fromJson(json['generation-i']) : null;
    generationIi = (json['generation-ii'] != null) ? PokemonDetailModelSpritesVersionsGenerationIi.fromJson(json['generation-ii']) : null;
    generationIii = (json['generation-iii'] != null) ? PokemonDetailModelSpritesVersionsGenerationIii.fromJson(json['generation-iii']) : null;
    generationIv = (json['generation-iv'] != null) ? PokemonDetailModelSpritesVersionsGenerationIv.fromJson(json['generation-iv']) : null;
    generationV = (json['generation-v'] != null) ? PokemonDetailModelSpritesVersionsGenerationV.fromJson(json['generation-v']) : null;
    generationVi = (json['generation-vi'] != null) ? PokemonDetailModelSpritesVersionsGenerationVi.fromJson(json['generation-vi']) : null;
    generationVii = (json['generation-vii'] != null) ? PokemonDetailModelSpritesVersionsGenerationVii.fromJson(json['generation-vii']) : null;
    generationViii = (json['generation-viii'] != null) ? PokemonDetailModelSpritesVersionsGenerationViii.fromJson(json['generation-viii']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (generationI != null) {
      data['generation-i'] = generationI!.toJson();
    }
    if (generationIi != null) {
      data['generation-ii'] = generationIi!.toJson();
    }
    if (generationIii != null) {
      data['generation-iii'] = generationIii!.toJson();
    }
    if (generationIv != null) {
      data['generation-iv'] = generationIv!.toJson();
    }
    if (generationV != null) {
      data['generation-v'] = generationV!.toJson();
    }
    if (generationVi != null) {
      data['generation-vi'] = generationVi!.toJson();
    }
    if (generationVii != null) {
      data['generation-vii'] = generationVii!.toJson();
    }
    if (generationViii != null) {
      data['generation-viii'] = generationViii!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpritesOtherOfficialArtwork {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/21.png",
  "front_shiny": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/shiny/21.png"
} 
*/

  String? frontDefault;
  String? frontShiny;

  PokemonDetailModelSpritesOtherOfficialArtwork({
    this.frontDefault,
    this.frontShiny,
  });
  PokemonDetailModelSpritesOtherOfficialArtwork.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontShiny = json['front_shiny']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_shiny'] = frontShiny;
    return data;
  }
}

class PokemonDetailModelSpritesOtherHome {

  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;

  PokemonDetailModelSpritesOtherHome({
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
  });
  PokemonDetailModelSpritesOtherHome.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    return data;
  }
}

class PokemonDetailModelSpritesOtherDreamWorld {
/*
{
  "front_default": "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/21.svg",
  "front_female": null
} 
*/

  String? frontDefault;
  String? frontFemale;

  PokemonDetailModelSpritesOtherDreamWorld({
    this.frontDefault,
    this.frontFemale,
  });
  PokemonDetailModelSpritesOtherDreamWorld.fromJson(Map<String, dynamic> json) {
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    return data;
  }
}

class PokemonDetailModelSpritesOther {
  PokemonDetailModelSpritesOtherDreamWorld? dreamWorld;
  PokemonDetailModelSpritesOtherHome? home;
  PokemonDetailModelSpritesOtherOfficialArtwork? officialArtwork;

  PokemonDetailModelSpritesOther({
    this.dreamWorld,
    this.home,
    this.officialArtwork,
  });
  PokemonDetailModelSpritesOther.fromJson(Map<String, dynamic> json) {
    dreamWorld = (json['dream_world'] != null) ? PokemonDetailModelSpritesOtherDreamWorld.fromJson(json['dream_world']) : null;
    home = (json['home'] != null) ? PokemonDetailModelSpritesOtherHome.fromJson(json['home']) : null;
    officialArtwork = (json['official-artwork'] != null) ? PokemonDetailModelSpritesOtherOfficialArtwork.fromJson(json['official-artwork']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (dreamWorld != null) {
      data['dream_world'] = dreamWorld!.toJson();
    }
    if (home != null) {
      data['home'] = home!.toJson();
    }
    if (officialArtwork != null) {
      data['official-artwork'] = officialArtwork!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSprites {

  String? backDefault;
  String? backFemale;
  String? backShiny;
  String? backShinyFemale;
  String? frontDefault;
  String? frontFemale;
  String? frontShiny;
  String? frontShinyFemale;
  PokemonDetailModelSpritesOther? other;
  PokemonDetailModelSpritesVersions? versions;

  PokemonDetailModelSprites({
    this.backDefault,
    this.backFemale,
    this.backShiny,
    this.backShinyFemale,
    this.frontDefault,
    this.frontFemale,
    this.frontShiny,
    this.frontShinyFemale,
    this.other,
    this.versions,
  });
  PokemonDetailModelSprites.fromJson(Map<String, dynamic> json) {
    backDefault = json['back_default']?.toString();
    backFemale = json['back_female']?.toString();
    backShiny = json['back_shiny']?.toString();
    backShinyFemale = json['back_shiny_female']?.toString();
    frontDefault = json['front_default']?.toString();
    frontFemale = json['front_female']?.toString();
    frontShiny = json['front_shiny']?.toString();
    frontShinyFemale = json['front_shiny_female']?.toString();
    other = (json['other'] != null) ? PokemonDetailModelSpritesOther.fromJson(json['other']) : null;
    versions = (json['versions'] != null) ? PokemonDetailModelSpritesVersions.fromJson(json['versions']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['back_default'] = backDefault;
    data['back_female'] = backFemale;
    data['back_shiny'] = backShiny;
    data['back_shiny_female'] = backShinyFemale;
    data['front_default'] = frontDefault;
    data['front_female'] = frontFemale;
    data['front_shiny'] = frontShiny;
    data['front_shiny_female'] = frontShinyFemale;
    if (other != null) {
      data['other'] = other!.toJson();
    }
    if (versions != null) {
      data['versions'] = versions!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelSpecies {
/*
{
  "name": "spearow",
  "url": "https://pokeapi.co/api/v2/pokemon-species/21/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelSpecies({
    this.name,
    this.url,
  });
  PokemonDetailModelSpecies.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelMovesVersionGroupDetailsVersionGroup {
/*
{
  "name": "red-blue",
  "url": "https://pokeapi.co/api/v2/version-group/1/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelMovesVersionGroupDetailsVersionGroup({
    this.name,
    this.url,
  });
  PokemonDetailModelMovesVersionGroupDetailsVersionGroup.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelMovesVersionGroupDetailsMoveLearnMethod {
/*
{
  "name": "machine",
  "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelMovesVersionGroupDetailsMoveLearnMethod({
    this.name,
    this.url,
  });
  PokemonDetailModelMovesVersionGroupDetailsMoveLearnMethod.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelMovesVersionGroupDetails {
/*
{
  "level_learned_at": 0,
  "move_learn_method": {
    "name": "machine",
    "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
  },
  "version_group": {
    "name": "red-blue",
    "url": "https://pokeapi.co/api/v2/version-group/1/"
  }
} 
*/

  int? levelLearnedAt;
  PokemonDetailModelMovesVersionGroupDetailsMoveLearnMethod? moveLearnMethod;
  PokemonDetailModelMovesVersionGroupDetailsVersionGroup? versionGroup;

  PokemonDetailModelMovesVersionGroupDetails({
    this.levelLearnedAt,
    this.moveLearnMethod,
    this.versionGroup,
  });
  PokemonDetailModelMovesVersionGroupDetails.fromJson(Map<String, dynamic> json) {
    levelLearnedAt = json['level_learned_at']?.toInt();
    moveLearnMethod = (json['move_learn_method'] != null) ? PokemonDetailModelMovesVersionGroupDetailsMoveLearnMethod.fromJson(json['move_learn_method']) : null;
    versionGroup = (json['version_group'] != null) ? PokemonDetailModelMovesVersionGroupDetailsVersionGroup.fromJson(json['version_group']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['level_learned_at'] = levelLearnedAt;
    if (moveLearnMethod != null) {
      data['move_learn_method'] = moveLearnMethod!.toJson();
    }
    if (versionGroup != null) {
      data['version_group'] = versionGroup!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelMovesMove {
/*
{
  "name": "razor-wind",
  "url": "https://pokeapi.co/api/v2/move/13/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelMovesMove({
    this.name,
    this.url,
  });
  PokemonDetailModelMovesMove.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelMoves {
/*
{
  "move": {
    "name": "razor-wind",
    "url": "https://pokeapi.co/api/v2/move/13/"
  },
  "version_group_details": [
    {
      "level_learned_at": 0,
      "move_learn_method": {
        "name": "machine",
        "url": "https://pokeapi.co/api/v2/move-learn-method/4/"
      },
      "version_group": {
        "name": "red-blue",
        "url": "https://pokeapi.co/api/v2/version-group/1/"
      }
    }
  ]
} 
*/

  PokemonDetailModelMovesMove? move;
  List<PokemonDetailModelMovesVersionGroupDetails?>? versionGroupDetails;

  PokemonDetailModelMoves({
    this.move,
    this.versionGroupDetails,
  });
  PokemonDetailModelMoves.fromJson(Map<String, dynamic> json) {
    move = (json['move'] != null) ? PokemonDetailModelMovesMove.fromJson(json['move']) : null;
  if (json['version_group_details'] != null) {
  final v = json['version_group_details'];
  final arr0 = <PokemonDetailModelMovesVersionGroupDetails>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelMovesVersionGroupDetails.fromJson(v));
  });
    versionGroupDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (move != null) {
      data['move'] = move!.toJson();
    }
    if (versionGroupDetails != null) {
      final v = versionGroupDetails;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['version_group_details'] = arr0;
    }
    return data;
  }
}

class PokemonDetailModelHeldItemsVersionDetailsVersion {
/*
{
  "name": "sun",
  "url": "https://pokeapi.co/api/v2/version/27/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelHeldItemsVersionDetailsVersion({
    this.name,
    this.url,
  });
  PokemonDetailModelHeldItemsVersionDetailsVersion.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelHeldItemsVersionDetails {
/*
{
  "rarity": 5,
  "version": {
    "name": "sun",
    "url": "https://pokeapi.co/api/v2/version/27/"
  }
} 
*/

  int? rarity;
  PokemonDetailModelHeldItemsVersionDetailsVersion? version;

  PokemonDetailModelHeldItemsVersionDetails({
    this.rarity,
    this.version,
  });
  PokemonDetailModelHeldItemsVersionDetails.fromJson(Map<String, dynamic> json) {
    rarity = json['rarity']?.toInt();
    version = (json['version'] != null) ? PokemonDetailModelHeldItemsVersionDetailsVersion.fromJson(json['version']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['rarity'] = rarity;
    if (version != null) {
      data['version'] = version!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelHeldItemsItem {
/*
{
  "name": "sharp-beak",
  "url": "https://pokeapi.co/api/v2/item/221/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelHeldItemsItem({
    this.name,
    this.url,
  });
  PokemonDetailModelHeldItemsItem.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelHeldItems {
/*
{
  "item": {
    "name": "sharp-beak",
    "url": "https://pokeapi.co/api/v2/item/221/"
  },
  "version_details": [
    {
      "rarity": 5,
      "version": {
        "name": "sun",
        "url": "https://pokeapi.co/api/v2/version/27/"
      }
    }
  ]
} 
*/

  PokemonDetailModelHeldItemsItem? item;
  List<PokemonDetailModelHeldItemsVersionDetails?>? versionDetails;

  PokemonDetailModelHeldItems({
    this.item,
    this.versionDetails,
  });
  PokemonDetailModelHeldItems.fromJson(Map<String, dynamic> json) {
    item = (json['item'] != null) ? PokemonDetailModelHeldItemsItem.fromJson(json['item']) : null;
  if (json['version_details'] != null) {
  final v = json['version_details'];
  final arr0 = <PokemonDetailModelHeldItemsVersionDetails>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelHeldItemsVersionDetails.fromJson(v));
  });
    versionDetails = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (item != null) {
      data['item'] = item!.toJson();
    }
    if (versionDetails != null) {
      final v = versionDetails;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['version_details'] = arr0;
    }
    return data;
  }
}

class PokemonDetailModelGameIndicesVersion {
/*
{
  "name": "red",
  "url": "https://pokeapi.co/api/v2/version/1/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelGameIndicesVersion({
    this.name,
    this.url,
  });
  PokemonDetailModelGameIndicesVersion.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelGameIndices {
/*
{
  "game_index": 5,
  "version": {
    "name": "red",
    "url": "https://pokeapi.co/api/v2/version/1/"
  }
} 
*/

  int? gameIndex;
  PokemonDetailModelGameIndicesVersion? version;

  PokemonDetailModelGameIndices({
    this.gameIndex,
    this.version,
  });
  PokemonDetailModelGameIndices.fromJson(Map<String, dynamic> json) {
    gameIndex = json['game_index']?.toInt();
    version = (json['version'] != null) ? PokemonDetailModelGameIndicesVersion.fromJson(json['version']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['game_index'] = gameIndex;
    if (version != null) {
      data['version'] = version!.toJson();
    }
    return data;
  }
}

class PokemonDetailModelForms {
/*
{
  "name": "spearow",
  "url": "https://pokeapi.co/api/v2/pokemon-form/21/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelForms({
    this.name,
    this.url,
  });
  PokemonDetailModelForms.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelAbilitiesAbility {
/*
{
  "name": "keen-eye",
  "url": "https://pokeapi.co/api/v2/ability/51/"
} 
*/

  String? name;
  String? url;

  PokemonDetailModelAbilitiesAbility({
    this.name,
    this.url,
  });
  PokemonDetailModelAbilitiesAbility.fromJson(Map<String, dynamic> json) {
    name = json['name']?.toString();
    url = json['url']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['name'] = name;
    data['url'] = url;
    return data;
  }
}

class PokemonDetailModelAbilities {
/*
{
  "ability": {
    "name": "keen-eye",
    "url": "https://pokeapi.co/api/v2/ability/51/"
  },
  "is_hidden": false,
  "slot": 1
} 
*/

  PokemonDetailModelAbilitiesAbility? ability;
  bool? isHidden;
  int? slot;

  PokemonDetailModelAbilities({
    this.ability,
    this.isHidden,
    this.slot,
  });
  PokemonDetailModelAbilities.fromJson(Map<String, dynamic> json) {
    ability = (json['ability'] != null) ? PokemonDetailModelAbilitiesAbility.fromJson(json['ability']) : null;
    isHidden = json['is_hidden'];
    slot = json['slot']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (ability != null) {
      data['ability'] = ability!.toJson();
    }
    data['is_hidden'] = isHidden;
    data['slot'] = slot;
    return data;
  }
}

class PokemonDetailModel {

  List<PokemonDetailModelAbilities?>? abilities;
  int? baseExperience;
  List<PokemonDetailModelForms?>? forms;
  List<PokemonDetailModelGameIndices?>? gameIndices;
  int? height;
  List<PokemonDetailModelHeldItems?>? heldItems;
  int? id;
  bool? isDefault;
  String? locationAreaEncounters;
  List<PokemonDetailModelMoves?>? moves;
  String? name;
  int? order;
  PokemonDetailModelSpecies? species;
  PokemonDetailModelSprites? sprites;
  List<PokemonDetailModelStats?>? stats;
  List<PokemonDetailModelTypes?>? types;
  int? weight;

  PokemonDetailModel({
    this.abilities,
    this.baseExperience,
    this.forms,
    this.gameIndices,
    this.height,
    this.heldItems,
    this.id,
    this.isDefault,
    this.locationAreaEncounters,
    this.moves,
    this.name,
    this.order,
    this.species,
    this.sprites,
    this.stats,
    this.types,
    this.weight,
  });
  PokemonDetailModel.fromJson(Map<String, dynamic> json) {
  if (json['abilities'] != null) {
  final v = json['abilities'];
  final arr0 = <PokemonDetailModelAbilities>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelAbilities.fromJson(v));
  });
    abilities = arr0;
    }
    baseExperience = json['base_experience']?.toInt();
  if (json['forms'] != null) {
  final v = json['forms'];
  final arr0 = <PokemonDetailModelForms>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelForms.fromJson(v));
  });
    forms = arr0;
    }
  if (json['game_indices'] != null) {
  final v = json['game_indices'];
  final arr0 = <PokemonDetailModelGameIndices>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelGameIndices.fromJson(v));
  });
    gameIndices = arr0;
    }
    height = json['height']?.toInt();
  if (json['held_items'] != null) {
  final v = json['held_items'];
  final arr0 = <PokemonDetailModelHeldItems>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelHeldItems.fromJson(v));
  });
    heldItems = arr0;
    }
    id = json['id']?.toInt();
    isDefault = json['is_default'];
    locationAreaEncounters = json['location_area_encounters']?.toString();
  if (json['moves'] != null) {
  final v = json['moves'];
  final arr0 = <PokemonDetailModelMoves>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelMoves.fromJson(v));
  });
    moves = arr0;
    }
    name = json['name']?.toString();
    order = json['order']?.toInt();
    species = (json['species'] != null) ? PokemonDetailModelSpecies.fromJson(json['species']) : null;
    sprites = (json['sprites'] != null) ? PokemonDetailModelSprites.fromJson(json['sprites']) : null;
  if (json['stats'] != null) {
  final v = json['stats'];
  final arr0 = <PokemonDetailModelStats>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelStats.fromJson(v));
  });
    stats = arr0;
    }
  if (json['types'] != null) {
  final v = json['types'];
  final arr0 = <PokemonDetailModelTypes>[];
  v.forEach((v) {
  arr0.add(PokemonDetailModelTypes.fromJson(v));
  });
    types = arr0;
    }
    weight = json['weight']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (abilities != null) {
      final v = abilities;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['abilities'] = arr0;
    }
    data['base_experience'] = baseExperience;
    if (forms != null) {
      final v = forms;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['forms'] = arr0;
    }
    if (gameIndices != null) {
      final v = gameIndices;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['game_indices'] = arr0;
    }
    data['height'] = height;
    if (heldItems != null) {
      final v = heldItems;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['held_items'] = arr0;
    }
    data['id'] = id;
    data['is_default'] = isDefault;
    data['location_area_encounters'] = locationAreaEncounters;
    if (moves != null) {
      final v = moves;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['moves'] = arr0;
    }
    data['name'] = name;
    data['order'] = order;
    if (species != null) {
      data['species'] = species!.toJson();
    }
    if (sprites != null) {
      data['sprites'] = sprites!.toJson();
    }
    if (stats != null) {
      final v = stats;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['stats'] = arr0;
    }
    if (types != null) {
      final v = types;
      final arr0 = [];
  for (var v in v!) {
  arr0.add(v!.toJson());
  }
      data['types'] = arr0;
    }
    data['weight'] = weight;
    return data;
  }
}
